/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FooterRouteImport } from './routes/_footer'
import { Route as FooterIndexRouteImport } from './routes/_footer/index'
import { Route as RecipesIdRouteImport } from './routes/recipes/$id'
import { Route as ListCreateRouteImport } from './routes/list/create'
import { Route as FooterAddRouteImport } from './routes/_footer/add'
import { Route as FooterRecipesIndexRouteImport } from './routes/_footer/recipes/index'
import { Route as FooterListIndexRouteImport } from './routes/_footer/list/index'

const FooterRoute = FooterRouteImport.update({
  id: '/_footer',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterIndexRoute = FooterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FooterRoute,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListCreateRoute = ListCreateRouteImport.update({
  id: '/list/create',
  path: '/list/create',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterAddRoute = FooterAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => FooterRoute,
} as any)
const FooterRecipesIndexRoute = FooterRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => FooterRoute,
} as any)
const FooterListIndexRoute = FooterListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => FooterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof FooterIndexRoute
  '/add': typeof FooterAddRoute
  '/list/create': typeof ListCreateRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/list/': typeof FooterListIndexRoute
  '/recipes/': typeof FooterRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/add': typeof FooterAddRoute
  '/list/create': typeof ListCreateRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/': typeof FooterIndexRoute
  '/list': typeof FooterListIndexRoute
  '/recipes': typeof FooterRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_footer': typeof FooterRouteWithChildren
  '/_footer/add': typeof FooterAddRoute
  '/list/create': typeof ListCreateRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/_footer/': typeof FooterIndexRoute
  '/_footer/list/': typeof FooterListIndexRoute
  '/_footer/recipes/': typeof FooterRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/list/create'
    | '/recipes/$id'
    | '/list/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/add' | '/list/create' | '/recipes/$id' | '/' | '/list' | '/recipes'
  id:
    | '__root__'
    | '/_footer'
    | '/_footer/add'
    | '/list/create'
    | '/recipes/$id'
    | '/_footer/'
    | '/_footer/list/'
    | '/_footer/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FooterRoute: typeof FooterRouteWithChildren
  ListCreateRoute: typeof ListCreateRoute
  RecipesIdRoute: typeof RecipesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_footer': {
      id: '/_footer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_footer/': {
      id: '/_footer/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FooterIndexRouteImport
      parentRoute: typeof FooterRoute
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/create': {
      id: '/list/create'
      path: '/list/create'
      fullPath: '/list/create'
      preLoaderRoute: typeof ListCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_footer/add': {
      id: '/_footer/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof FooterAddRouteImport
      parentRoute: typeof FooterRoute
    }
    '/_footer/recipes/': {
      id: '/_footer/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof FooterRecipesIndexRouteImport
      parentRoute: typeof FooterRoute
    }
    '/_footer/list/': {
      id: '/_footer/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof FooterListIndexRouteImport
      parentRoute: typeof FooterRoute
    }
  }
}

interface FooterRouteChildren {
  FooterAddRoute: typeof FooterAddRoute
  FooterIndexRoute: typeof FooterIndexRoute
  FooterListIndexRoute: typeof FooterListIndexRoute
  FooterRecipesIndexRoute: typeof FooterRecipesIndexRoute
}

const FooterRouteChildren: FooterRouteChildren = {
  FooterAddRoute: FooterAddRoute,
  FooterIndexRoute: FooterIndexRoute,
  FooterListIndexRoute: FooterListIndexRoute,
  FooterRecipesIndexRoute: FooterRecipesIndexRoute,
}

const FooterRouteWithChildren =
  FooterRoute._addFileChildren(FooterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  FooterRoute: FooterRouteWithChildren,
  ListCreateRoute: ListCreateRoute,
  RecipesIdRoute: RecipesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
